version: 0.0.{build}
environment:
  APP_NAME: BulletMLI-Editor
  XAMARIN_COOKIE:
    secure: Ut8C5dcSVEh3A8IZHlj39DBV/bP4KCxzsnovjgt55gYc0OYlWQwP/fAwl7DFtdR4
  ANDROID_KEYSTORE_PASSWORD:
    secure: vCt3VttSDKvDmKmtNCqB4ufbBxhbvzALFXZ8unuvDU8=
  HOCKEYAPP_APP_ID:
    secure: fpr1QScg5nnut+f1Ohzco8kehEfA5HJqP9hMoDx0hZr6Oer9sMdCKNh1na6RKKfJ
  HOCKEYAPP_API_TOKEN:
    secure: j0zM29SX82jirzfqpDjMKLVDuGCtnnhjAlfCW9VW13WihwhSyfJTzRmmqb4pjojM
  ANDROID_KEYSTORE_ALIAS:
    secure: n8AJ+/2dLtjovNej5PHJ1g==
  ANDROID_PROJECT_PATH: Editor.Android
  ANDROID_PROJECT_FILENAME: Editor.Android.csproj
  ANDROID_KEYSTORE_PATH: Keystore\BulletMLI-Editor.keystore
  DESKTOP_PROJECT_PATH: Editor.Desktop
  DESKTOP_PROJECT_FILENAME: Editor.Desktop.csproj
  GITHUB_DEPLOY_KEY:
    secure: cu4EiJJNEyxgZBvCZ4N0j0DvSqY6Omi5zruSosvK2t0vw2QnKFbNcxacF+M27WB7
platform: Any CPU
configuration: Release
install:
  - git submodule update --init --recursive
  - ps: '& ./Scripts/InstallDependencies.ps1'
before_build:
  - xamarin-component.exe restore "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%"
  - nuget restore -PackagesDirectory "packages"
build:
  parallel: true
  project: '%DESKTOP_PROJECT_PATH%\%DESKTOP_PROJECT_FILENAME%'
  verbosity: minimal
after_build:
  - rename "%APPVEYOR_BUILD_FOLDER%\%DESKTOP_PROJECT_PATH%\bin\DesktopGL\AnyCPU\Release\Editor.Desktop.exe" "%APP_NAME%-v%APPVEYOR_BUILD_VERSION%.exe"
  - 7z a "%APP_NAME%-v%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%\%DESKTOP_PROJECT_PATH%\bin\DesktopGL\AnyCPU\Release\*"
artifacts:
  - path: '%APP_NAME%-v%APPVEYOR_BUILD_VERSION%.zip'
    name: '%APP_NAME%'
deploy:
  release: BulletMLI-Editor-v$(appveyor_build_version)
  description: 'v$(appveyor_build_version)'
  provider: GitHub
  auth_token: '%GITHUB_DEPLOY_KEY%'
  artifact: '%APP_NAME%-v%APPVEYOR_BUILD_VERSION%.zip'
  draft: false
  prerelease: false
  on:
    branch: desktop                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only