version: 0.0.{build}
environment:
  XAMARIN_COOKIE:
    secure: Ut8C5dcSVEh3A8IZHlj39DBV/bP4KCxzsnovjgt55gYc0OYlWQwP/fAwl7DFtdR4
  ANDROID_KEYSTORE_PASSWORD:
    secure: vCt3VttSDKvDmKmtNCqB4ufbBxhbvzALFXZ8unuvDU8=
  HOCKEYAPP_APP_ID:
    secure: fpr1QScg5nnut+f1Ohzco8kehEfA5HJqP9hMoDx0hZr6Oer9sMdCKNh1na6RKKfJ
  HOCKEYAPP_API_TOKEN:
    secure: j0zM29SX82jirzfqpDjMKLVDuGCtnnhjAlfCW9VW13WihwhSyfJTzRmmqb4pjojM
  ANDROID_KEYSTORE_ALIAS:
    secure: n8AJ+/2dLtjovNej5PHJ1g==
  ANDROID_PROJECT_PATH: Editor.Android
  ANDROID_PROJECT_FILENAME: Editor.Android.csproj
  ANDROID_KEYSTORE_PATH: Keystore\BulletMLI-Editor.keystore
  APP_NAME: BulletMLI-Editor
install:
  - git submodule update --init --recursive
  - ps: '& ./Scripts/InstallDependencies.ps1'
before_build:
  - xamarin-component.exe restore "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%"
  - nuget restore "%ANDROID_PROJECT_PATH%/.." -PackagesDirectory "%ANDROID_PROJECT_PATH%/../packages"
  - ps: '& ./Scripts/UpdateAndroidVersion.ps1'
build_script:
  - msbuild "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal /t:SignAndroidPackage /p:Configuration=Release /p:Platform=AnyCPU /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias="%ANDROID_KEYSTORE_ALIAS%" /p:AndroidSigningKeyPass="%ANDROID_KEYSTORE_PASSWORD%" /p:AndroidSigningKeyStore="%APPVEYOR_BUILD_FOLDER%\%ANDROID_KEYSTORE_PATH%" /p:AndroidSigningStorePass="%ANDROID_KEYSTORE_PASSWORD%"
  - rename "%APPVEYOR_BUILD_FOLDER%\%ANDROID_PROJECT_PATH%\bin\Android\AnyCPU\Release\Editor.Android-Signed.apk" "%APP_NAME%-%APPVEYOR_BUILD_NUMBER%.apk"
artifacts:
  - path: '%ANDROID_PROJECT_PATH%\bin\Android\AnyCPU\Release\%APP_NAME%-%APPVEYOR_BUILD_NUMBER%.apk'
    name: '%APP_NAME%'
deploy_script:
  - ps: '& ./Scripts/AndroidHockeyAppUpload.ps1'